### ISSUE TITLE
Terminology: Inference/Deduction

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#128]
I reviewed the changes made according to #116: that's fine now!

However, I began to wonder about the ternminology on reading "this is the deduction form we are trying to turn into theorem form". Is the term "deduction" correctly used?
In the book, we have the following definitions at the beginning of chapter 3.9:
> a deduction (also called an inference) is a kind of statement
> that needs some hypotheses to be true in order for its conclusion to be
> true. A theorem, on the other hand, has no hypotheses.

In set.mm, however, we have:
>   We will use the following descriptive terms very loosely:  A "closed form" or
>   "tautology" has no $e hypotheses.  An "inference" has one or more $e
>   hypotheses.  A "deduction" is an inference in which the hypotheses and the
>   conclusion share the same antecedent.

In this way, the comments are written, e.g. ~ unssad (deduction form of ~ unss).  I think there is a discrepancy in the usage of the terms: According to the book, "deduction" and "inference" denote the same, whereas according to set.mm, a "deduction" is a special "inference", meaning that there are "inferences" which are not deductions (such theorems have usually suffix i in set.mm).

In the comment for ~ a1d, there is a clear distinction between "deductions" ("the hypotheses and conclusion are each prefixed with the same antecedent") and "inferences" ("simpler version with no common antecedent"). I think this could be the best starting point for a "classification" of theorems:

- **Deductions**: Theorems having hypotheses, and hypotheses and conclusion are each prefixed with the same antecedent.
- **Inferences**: Theorems having hypotheses, and hypotheses and conclusion do not have a common antecedent.
- **Theorems in closed form** or **Tautologies**: Theorems having no hypotheses

However, reading chapter 3.9 in more detail, there could be the following definition:
- **Deduction style theorems**: Theorems having hypotheses, and hypotheses and conclusion are each prefixed with the same antecedent.
- **Deductions** or "Inferences": Theorems having hypotheses, and hypotheses and conclusion (usually) do not have a common antecedent.
- **Theorems in closed form** (or simply **Theorems**) or **Tautologies**: Theorems having no hypotheses

In any case, we either have to update the book or set.mm...

**Comment by avekens** [comment]
... having a look at http://us.metamath.org/mpeuni/mmnatded.html, we hopefully can agree on the following classifications of theorems:

- **deduction form**: Theorems having hypotheses, and hypotheses (except definitions) and conclusion are each prefixed with the same antecedent.
- **inference form": Theorems having hypotheses, and hypotheses and conclusion do not have a common antecedent.
- **closed form**: Theorems having no hypotheses

This also corresponds to the definitions in section 3.9.3. Maybe these definitions should be presented earlier (e.g. at the beginning of chapter 3.9),

**Comment by nmegill** [comment]
While this isn't the final word, let me try to clarify the language a little.  I think that in ordinary logic there are 3 concepts:  inference rules, deductions, and closed theorems (although the adjective "closed" could be a Metamath thing, not sure).  Some people might call closed theorems "tautologies" although I don't recall seeing that used outside of propositional or at most predicate logic; for example I don't recall seeing set theory theorems called tautologies.

An inference rule has one or more hypotheses that need to be proved before the conclusion can be inferred.  An example is modus ponens:  |- phi and |- (phi -> psi) imply |- psi.  To discharge the two hypotheses, we need to prove both |- phi and |- (phi -> psi).

A deduction (in ordinary logic) has assumptions that are presupposed in order to arrive at a conclusion:  phi |- psi means that phi can be assumed (i.e. used as a proof step) in the course of the proof of psi.  However, we don't need to prove phi as a theorem (and it needn't be a theorem) in order to discharge it.  Instead, we invoke the standard deduction theorem to transform phi into an antecedent, resulting in the closed theorem  |- (phi -> psi).

Presumably (in ordinary logic) we can have a statement that is both an inference rule (with hypotheses) and a deduction (with an assumption list attached to the conclusion or even the hypotheses), although I don't know what such a compound statement would be called.

In set.mm we don't have true deductions and don't even have a notation to support them.  Instead, we simply work with |- (phi -> psi) directly.  When we have an inference with hypotheses also having the antecedent phi, we have been calling these "deductions" or "deduction form" even though they are really a specialized kind of inference.

**Comment by david-a-wheeler** [comment]
So does something need to be changed in the metamath book text? Or are things clear enough?

**Comment by nmegill** [comment]
I think it is clear enough.  Off hand I don't see a misuse.  Basically I wanted to distinguish the notions of inference vs. deduction as (I think) they are used in the literature.

In various places I think we use "deduction form", "deduction style", and "deduction method" to mean the same thing.  Should we settle on a single terminology?  I like "deduction form" but am open to the others.

Aside from this, we might as well close the issue.

**Comment by avekens** [comment]
I think the explanations and usage of the terminology is fine (I agree, however, with Norm to use consistently "deduction form" instead of "deduction style").  So this issue could be closed if the alignment according to Norm's proposal are done.

Maybe we should adjust/update some comments in set.mm afterwards to be consistent with the book.

**Comment by avekens** [comment]
Sorry, I closed the issue accidentally!

**Comment by david-a-wheeler** [comment]
We need to change "theorem" to "assertion" if we're going to use these in section 3.9.

**Comment by david-a-wheeler** [comment]
Perhaps we should change "theorem" in these definitions to "statement", as that's the term used in the 3.9 intro.

**Comment by david-a-wheeler** [comment]
I should probably wait to comment until I'm awake :-).

Currently the terms "deduction form" and "deduction style" have *different* meanings, and I like it that way.  "Deduction form" is the specific form used for assertions.  "Deduction style" is the approach of using deduction form *instead* of using the weak deduction form.  So we can't just replace one with the other, the different terms have different meanings.  I think that should stay as-is.  If one term is accidentally being used for another, please point it out!

Section 3.9.3 already has the definitions of the three forms embedded as text. If we want to turn them into a bullet list that's fine, but I think it makes more sense to put in 3.9.3 (where the definitions are actually *needed*).  We can't say they're about "theorems" in section 3.9, though, because that section uses theorem in a more specific way (as explained at its beginning).  We also can't say "statements" because each hypothesis is a statement.  We can "assertions", that'd be fine.

**Comment by david-a-wheeler** [comment]
I will modify 3.9.3 so that the definitions are in bullets. That will make it more obvious where they are and their distinctions.

**Comment by david-a-wheeler** [comment]
It seems to me that we can clearly show that these are a taxonomy if inference form is simply an assertion with one or more hypotheses but is not in deduction form. Is that okay?

**Comment by david-a-wheeler** [comment]
I created a tweak in pull request #130 that I think addresses this.  This moves the 3 forms into a bullet list (which makes it more obvious that they are being contrasted).  I tweaked the definitions so that they clearly cover all cases.

**Comment by david-a-wheeler** [comment]
I think this has been addressed, closing.
