### ISSUE TITLE
Recommend increasing body font size for printed book to 11pt or 12pt

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#143]
@nmegill -

I think we should consider increasing the main body font size for the book from 10pt (current) to 11 or 12.

Currently the book is 10point, which is rather small for a book. I didn't see this problem earlier, sorry about that.  Earlier, when I read it on the screen or printed it to 8.5x11" paper, it was quite readable.  HOWEVER, what I didn't realize is that my PDF reader by default scales to the screen or page... so I was never seeing it at the size it will be in the printed book.

When I tell the system to *not* scale to the page size, 10pt is barely readable to me & I can only read it slowly (or take off my glasses and put my nose to the book).  I suspect others will have that problem too.  For a long work (like a book) a too-small font seems like a problem.

I tried out 3 different font sizes to compare the page counts:

- 10pt: 241 pages.
- 11pt: 289 pages
- 12pt: 327 pages

[At least one source says body text should be 10..12 inclusive](http://www.indesignskills.com/tutorials/book-font-size/). Hardcovers can be up to 800 pages, so there's no problem printing any of those.

Of the 3 options I'm leaning towards 11pt.  That is less likely to lead to bad line breaks, and it makes the book weigh a little less.  I think it's a reasonable compromise for a font size.

If we do switch, we'll need to recheck the result for bad line breaks.  However, I've tried to be careful to avoid things that presume any one width or font size, so it should not be a problem.

Comments?

**Comment by nmegill** [comment]
I looked at several technical books that I have, mostly paperback, and they seem to use around 10pt (sometimes even smaller) when they are a "smaller" (6x9-ish) size, and a larger font when they are expensive and heavy 8.5x11-ish college textbooks with glossy paper.  Novels often use a larger font, but that is a different category.  Perhaps you can look at some typical books in your collection to compare.

My original goal was a small, lightweight book that would be easy to carry around.  Hardcover defeats that to a certain extent, and ~300 pages even more so.  Neither is my personal preference.  But since I'm not the primary market, I will go along with what others prefer.  I think the question should be posed to the metamath group.

**Comment by david-a-wheeler** [comment]
I tried to get a fractional font (10.5), but it turns out that's not so easy in LaTeX.  You can easily ask for it:

~~~~
usepackage[fontsize=10.5]{scrextend}
~~~~

... but it won't work without regenerating fonts (ugh), and there are warnings about it (because the document class doesn't fully know about it).

I'll ask the group.  I think there's a modest preference for hardcover; it's more durable, and it also has the advantage of making it easier to "take seriously".  As you note, hardcover already makes it less lightweight.  I think its' 10pt vs. 11pt, and there are advantages to each.  I think 11pt is a little better, but there are clearly pluses and minuses to each.

**Comment by david-a-wheeler** [comment]
Looks like I'm the only one who would prefer 11pt, no one else seems to care.  My eyesight problems are my own I guess :-).  Switching to 11pt would require some fixes of some verbatim text, which is hard to justify if no one else cares.

It's easier to go with "what's already there", so I think we'll just do that.  So I'm closing this, and we'll leave it all as-is.
