### ISSUE TITLE
Number of Properties in Frames

### ISSUE THREAD

**Issue by EdwardMcCants** [metamath/metamath-book#202]
On Page 129, in section 4.2.7, Frames, there is a numbered list of 3 properties.

On Page 131, there is a sentence: "Properties 2, 3, and 4 for a frame also apply to an extended frame."

I don't think this has been shown in set.mm yet, but I'm pretty sure that it can be shown that:
` |- ( 3 == 4 -> F. )`
:smirk:

**Comment by nmegill** [comment]
There used to be a property between the present 2nd & 3rd:
```
  \item Each of the two variables in any {\tt \$d} statement must occur in a
{\tt \$f} statement.
```
which was removed because it is unnecessary and overly restrictive, however I'm unable to find the discussion and PR that removed this.  In any case, I believe "Properties 2, 3, and 4 for a frame also apply to an extended frame." should be changed to "Properties 2 and 3 for a frame also apply to an extended frame."  Do you agree this will fix the issue?

**Comment by vvs-** [comment]
> I'm unable to find the discussion and PR that removed this.

It was in #39.

**Comment by nmegill** [comment]
Thanks @EdwardMcCants and @vvs- .
I fiixed this in commit aab3a34.
