### ISSUE TITLE
Update Appendix A, "Math Symbol Tokens for Set Theory" ("$t appendix")

### ISSUE THREAD

**Issue by david-a-wheeler** [metamath/metamath-book#21]
Address this:

~~~~
  6/22/05 - metamath.tex - $t appendix
~~~~

Note: This TODO item isn't very clear - we need to first better understand it!

**Comment by david-a-wheeler** [comment]
I don't understand this comment, so I can't act on it.

@nmegill - can you or someone else explain what this is about? Otherwise I think we should just close it.

**Comment by david-a-wheeler** [comment]
See also the discussion in issue https://github.com/metamath/metamath-book/issues/15

**Comment by nmegill** [comment]
This was back in '05 but I pretty sure this meant to add an appendix, chapter, or section on the markup.  In particular I had the syntax and purpose of various $t commands in mind, but more generally describe all of the markup.  Perhaps Appendix A could be turned into a more comprehensive description (when it was written, only latexdef existed).

Also, the math symbol table in that Appendix is outdated, but I'm not sure if we should have a complete list (or even a list at all) since new definitions are added all the time.  Maybe just have a subset with the most familiar and most used symbols to help people get started, maybe just what can fit on one page for handy reference.  For example, we do not need the list of symbols used once in the complex number construction then discarded.  The book was written before the web pages existed, and now it's pretty easy to pin down the ASCII token for a symbol.

This is obviously a pretty big "to do" item, and it can be put on hold for now.

**Comment by david-a-wheeler** [comment]
Ah!!  *NOW* I understand.

I think we should *not* have a list of "all" set.mm symbols.  That will become instantly obsolete, while the web pages will be up-to-date and complete.

Here's a counter-proposal that is similar to your comments above:

1. Move the first page of the appendix, after updating, to the new `$t` subsection in the section on Metamath language extensions.  We should put all discussions about `$t` to one place.
2. Replace the current stuff with "a subset with some of the most used symbols to help people get started".  I envision a table with 3 columns: ASCII token, displayed symbol, and discussion.  The "Discussion" would provide an explanation of what the symbol is.... with comments useful for both those new to abstract math and those who are seasoned.  Worse comes to worse, I can copy-and-paste the explanation from set.mm for some symbols.  I *might* add a fourth column, the name of its primary definition (which would almost always be a df-...).  I say "primary" because I don't think we need to point to things like the 3-operand version of AND, and of course some things are primitives.

I think this change would make the appendix actually useful. It would also be easier to display on narrow displays.

**Comment by david-a-wheeler** [comment]
Also: I propose listing the ASCII token first in the table, and then sorting by that.  Sorting it that way will make it easy to look up ASCII symbols.

**Comment by david-a-wheeler** [comment]
Pull request #59 shows a possible replacement of material for Appendix A (I didn't remove the old stuff, so you can see them together in one document).  Please put your thoughts in PR #59.

**Comment by david-a-wheeler** [comment]
This is all done, so I'm closing this issue.
