### ISSUE TITLE
outdated output for assign command

### ISSUE THREAD

**Issue by avekens** [metamath/metamath-book#220]
In section 2.4 (and maybe also in other sections) an output ("To undo...")  is shown after performing an assign command (in the proof assistant) which I have never seen before:

MM-PA> assign 1 mp
To undo the assignment, DELETE STEP 5 and INITIALIZE, UNIFY if needed.

Was this a feature of a former version of metamath.exe? Or is there a flag I have to set for creating such outputs? I think in some cases it is quite useful to know the (new!) number of the last assigned step (currently I have to call "sh n/lem" to get it) for undoing the latest assignment. Therefore it would be fine if this feature will be reintroduced (optionally). Maybe the text should be a little bit shorter then, e.g. "assigned step got number 5".

Nevertheless, the book should be revised accordingly in the future.

**Comment by nmegill** [comment]
When the first edition of the book was written, metamath.exe didn't have the 'undo'/'redo' commands (added in 2013; see 'help undo'), so hints were provided by some commands for how to undo them manually.  These hints are no longer displayed since they are no longer needed, and it seems we overlooked that when updating the book.

@david-a-wheeler could you add this to the errata list when you get a chance?  Thanks.

Normally there isn't a need to know the new step number of the assigned step, because you can just type 'undo' to delete it and restore the state to exactly what it was prior to 'assign'.  After 'assign', 'show n/u' happens automatically and displays the (possibly renumbered) step numbers that still need to be assigned - those are the ones you ordinarily need to know.  It  also displays the easier-to-type negative small numbers relative to the last unknown step, to use with 'assign -3 ...' etc. (a feature suggested by O'Rear).

**Comment by avekens** [comment]
@nmegill Thank you for the hint - I was not aware that there is such an undo command. It does excatly what I need. Maybe (a part of) your explanation can also be included in the errata list and later into the book itself ...

**Comment by david-a-wheeler** [comment]
I've created an errata entry to resolve this in pull request https://github.com/metamath/metamath-book/pull/221

**Comment by avekens** [comment]
OK, done!
